artifact_location: /mnt/h/My Drive/2-Ciencia_de_datos/MLOps and MLflow/wine_quality_prediction/wine_quaility_mlflow/997226997576470917
creation_time: 1707600772480
experiment_id: '997226997576470917'
last_update_time: 1707600772480
lifecycle_stage: active
name: naive_regressor
