artifact_location: /mnt/h/My Drive/2-Ciencia_de_datos/MLOps and MLflow/wine_quality_prediction/wine_quaility_mlflow/227839945702505514
creation_time: 1707599683088
experiment_id: '227839945702505514'
last_update_time: 1707599683088
lifecycle_stage: active
name: experiment_1
