artifact_location: /mnt/i/My Drive/2-Ciencia_de_datos/MLOps and MLflow/wine_quality_prediction/wine_quaility_mlflow/620442977358808727
creation_time: 1707682766076
experiment_id: '620442977358808727'
last_update_time: 1707682766076
lifecycle_stage: active
name: naive_regressor_3
