artifact_location: /mnt/h/My Drive/2-Ciencia_de_datos/MLOps and MLflow/wine_quality_prediction/wine_quaility_mlflow/0
creation_time: 1707599682831
experiment_id: '0'
last_update_time: 1707599682831
lifecycle_stage: active
name: Default
