artifact_uri: /mnt/i/My Drive/2-Ciencia_de_datos/MLOps and MLflow/wine_quality_prediction/wine_quaility_mlflow/164611832355156529/a1fdac4c684a4c2f8baa96f5eb2dbcde/artifacts
end_time: 1707682660623
entry_point_name: ''
experiment_id: '164611832355156529'
lifecycle_stage: active
run_id: a1fdac4c684a4c2f8baa96f5eb2dbcde
run_name: persistent-shad-3
run_uuid: a1fdac4c684a4c2f8baa96f5eb2dbcde
source_name: ''
source_type: 4
source_version: ''
start_time: 1707682657411
status: 3
tags: []
user_id: ramiro
