artifact_location: /mnt/i/My Drive/2-Ciencia_de_datos/MLOps and MLflow/wine_quality_prediction/wine_quaility_mlflow/164611832355156529
creation_time: 1707682657018
experiment_id: '164611832355156529'
last_update_time: 1707682657018
lifecycle_stage: active
name: naive_regressor_2
